### ISSUE TITLE
TMDB language? 

### ISSUE THREAD

**Issue by lavara123** [kaledai/movie_db_app#35]
It would be better if it was with tmdb auto language code.

Good luck to you 👍

Example:
https://api.themoviedb.org/3/movie/popular?api_key={api_key}&language=en-US&page=1

**Comment by himmat12** [comment]
hello mate

auto language means you mean internationalization locales integrated ?!
if so then it will be there in future currently this project is still incomplete like 70% only integration done until now so wait until then it will be integrated in future ...

**Comment by lavara123** [comment]
> selam dostum
> 
> otomatik dil, uluslararasılaştırma yerel ayarlarının entegre olduğu anlamına mı geliyor?!
> eğer öyleyse o zaman gelecekte orada olacak şu anda bu proje hala tamamlanmamış %70 gibi sadece entegrasyon şimdiye kadar yapıldı, o zamana kadar bekleyin gelecekte entegre edilecek ...

**Comment by lavara123** [comment]
> hello mate
> 
> auto language means you mean internationalization locales integrated ?!
> if so then it will be there in future currently this project is still incomplete like 70% only integration done until now so wait until then it will be integrated in future ...

https://api.themoviedb.org/3/movie/popular?api_key={api_key}&page=1
To:
https://api.themoviedb.org/3/movie/popular?api_key={api_key}&language={lacale-code}&page=1

Good work 👍

**Comment by himmat12** [comment]
ok gotcha mate thanks for notifying the issue
