### ISSUE TITLE
An avalable tutorial for learners  ???

### ISSUE THREAD

**Issue by iblvck** [kaledai/movie_db_app#36]
Hey man,
This is a reall awesome project
we kindof new to flutter 
would be gald if you could provide a documentation on this project sir

Thanks in advance

**Comment by himmat12** [comment]
probably in future if this project gets much attention then only its worth investing time on documentig this prjct .. so stayed tuned but dont be sure that this will get written docs like i said if this gets more attention then i will make effort to write on doc but for now its still incomplete and under development so frst priority is to complete it ..

anyway thank you for your suggestion i will pin it on my todo list

**Comment by lavara123** [comment]
@kaledai When will the new update come?

**Comment by himmat12** [comment]
@lavara123 i will be a bit free from projects for a short period so im thinking of working on this project fro a while so you can expect some updates on this repo

**Comment by lavara123** [comment]
> @lavara123 kısa bir süre için projelerden biraz özgür olacağım, bu yüzden bir süre bu proje üzerinde çalışmayı düşünüyorum, böylece bu depoda bazı güncellemeler bekleyebilirsiniz

Thanks, I'm looking forward to it👍
