### ISSUE TITLE
Issue in search persitent on tab change from movie to tv and wise-versa

### ISSUE THREAD

**Issue by pranimation** [kaledai/movie_db_app#38]
_kudos to developer for making this app. It's looking good and feature rich._
 However I noticed 2 issues when i search something, it shows but as soon as i tap on (TV Series, Movies) menu it disappears.
Step to reproduce:
1 Search something on Movies Section
2 Tap on TV Series (**it will show no search but it should have results**) => issue 1
3 Again Tap on Movies and see **previous results gone**. =>issue 2

**Comment by lavara123** [comment]
@himmat12 update?

**Comment by himmat12** [comment]
@pranimation thank you mate i will take it in note and fix it

**Comment by himmat12** [comment]
@lavara123 as for update i'm not sure weather i will be continuing this project in future so i'm not sure so i will left rest of the new feratures and stuffs to you guys explore it and add it as your own in your personal repo anyway thnks mate for following through this until now

**Comment by himmat12** [comment]
@pranimation pull the latest patches then test any give me review i think i ve fixed that issue along with others search related bugs too
